//This file is generated by bin/hook.js
var template = require('template');
module.exports = {

  CSS: {
    
      'rtmp_hls': '#rtmp-hls {	width: 100%;	height: 100%;}[data-hls] {	visibility: hidden;}',
    
  }
};
